x-app-db-url: &app_db_url mongodb://mongo:27017/movie_tickets?replicaSet=rs0

services:

  mongo:
    image: mongo:7
    container_name: movie_tickets_mongo
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-rs-init:
    image: mongo:7
    container_name: movie_tickets_mongo_rs_init
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      - mongosh
      - --host
      - mongo:27017
      - --quiet
      - --eval
      - >
        try {
          rs.status();
        } catch (e) {
          rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "mongo:27017" }] });
        }

  app:
    build:
      context: ..
      dockerfile: composes/Dockerfile
      args:
        DATABASE_URL: *app_db_url
    container_name: movie_tickets_app
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      mongo-rs-init:
        condition: service_completed_successfully
    env_file:
      - ../.env
    environment:
      DATABASE_URL: *app_db_url
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  mongo_data:
